  # Loads default set of integrations. Do not remove.
  default_config:

  # Load frontend themes from the themes folder
  frontend:
    themes: !include_dir_merge_named themes

  automation: !include automations.yaml
  script: !include scripts.yaml
  scene: !include scenes.yaml

  http:
    use_x_forwarded_for: true
    trusted_proxies:
      - 172.30.33.2

  shell_command:
    light_kitchen_headlights_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchenHeadlights=1&actionKitchen=Switch%20Off"'
    light_kitchen_headlights_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchenHeadlights=1&actionKitchen=Switch%20On"'
    light_kitchen_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=Switch%20Off"'
    light_kitchen_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=Switch%20On"'
    light_kitchen_10: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=10"'
    light_kitchen_20: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=20"'
    light_kitchen_30: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=30"'
    light_kitchen_40: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=40"'
    light_kitchen_50: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=50"'
    light_kitchen_60: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=60"'
    light_kitchen_70: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=70"'
    light_kitchen_80: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=80"'
    light_kitchen_90: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=90"'
    light_kitchen_100: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=100"'
    
    light_bathroom_headlights_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroomHeadlights=1&actionBathroom=Switch%20Off"'
    light_bathroom_headlights_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroomHeadlights=1&actionBathroom=Switch%20On"'
    light_bathroom_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=Switch%20Off"'
    light_bathroom_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=Switch%20On"'
    light_bathroom_10: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=10"'
    light_bathroom_20: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=20"'
    light_bathroom_30: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=30"'
    light_bathroom_40: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=40"'
    light_bathroom_50: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=50"'
    light_bathroom_60: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=60"'
    light_bathroom_70: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=70"'
    light_bathroom_80: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=80"'
    light_bathroom_90: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=90"'
    light_bathroom_100: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=100"'

    light_entrance_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withEntrance=1&actionEntrance=Switch%20Off"'
    light_entrance_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withEntrance=1&actionEntrance=Switch%20On"'
    
    light_loggia_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withLoggia=1&actionLoggia=Switch%20Off"'
    light_loggia_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withLoggia=1&actionLoggia=Switch%20On"'

    ventilation_bedroom_0: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Aus"'
    ventilation_bedroom_1: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Stufe 1"'
    ventilation_bedroom_2: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Stufe 2"'
    ventilation_bedroom_3: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Stufe 3"'
    ventilation_bedroom_4: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Stufe 4"'
    
    ventilation_livingroom_0: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Aus"'
    ventilation_livingroom_1: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Stufe 1"'
    ventilation_livingroom_2: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Stufe 2"'
    ventilation_livingroom_3: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Stufe 3"'
    ventilation_livingroom_4: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Stufe 4"'
    
    shades_loggia_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1,2&setLoggia1=0&setLoggia2=0"'
    shades_loggia_60: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1,2&setLoggia1=60&setLoggia2=60"'
    shades_loggia_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1,2&setLoggia1=100&setLoggia2=100"'
    shades_loggia_side1_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1&setLoggia1=0"'
    shades_loggia_side1_60: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1&setLoggia1=60"'
    shades_loggia_side1_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1&setLoggia1=100"'
    shades_loggia_side2_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=2&setLoggia2=0"'
    shades_loggia_side2_60: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=2&setLoggia2=60"'
    shades_loggia_side2_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=2&setLoggia2=100"'
    
    shades_bedroom_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&setBedroom=0"'
    shades_bedroom_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&setBedroom=60&tiltBedroom=1"'
    shades_bedroom_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&setBedroom=100&tiltBedroom=0"'    
    
    shades_kitchen_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&setKitchen=0"'
    shades_kitchen_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&setKitchen=60&tiltKitchen=1"'
    shades_kitchen_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&setKitchen=100&tiltKitchen=0"'
   
    shades_livingroom_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=3&set3=0"'
    shades_livingroom_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=3&set3=60"'
    shades_livingroom_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=3&set3=100&tilt3=0"'
    
    shades_loggiawindow_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=4&set4=0"'
    shades_loggiawindow_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=4&set4=60&titlt4=1"'
    shades_loggiawindow_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=4&set4=100&titlt4=0"'
    
    shades_livingroom_0_loggia_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=3,4&set3=0&set4=0"'
    shades_livingroom_60_1_loggia_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=3,4&set3=60&tilt3=1&set4=60&titlt4=1"'
    shades_livingroom_60_1_loggia_60_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=3,4&set3=60&tilt3=1&set4=60&titlt4=2"'
    shades_livingroom_100_loggia_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=3,4&set3=100&tilt3=0&set4=100&titlt4=0"'
    
    shades_office_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=2&set2=0"'
    shades_office_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=2&set2=60&titlt2=1"'
    shades_office_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&blockIndex=2&set2=100&titlt2=0"'

