
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
    use_x_forwarded_for: true
    trusted_proxies:
      - 172.30.33.2
      
# Shell commands
shell_command:
    light_kitchen_headlights_0: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/1/Switch%20Off"'
    light_kitchen_headlights_1: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/1/Switch%20On"'
    light_kitchen_0: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/Switch%20Off"'
    light_kitchen_1: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/Switch%20On"'
    light_kitchen_10: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/10"'
    light_kitchen_20: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/20"'
    light_kitchen_30: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/30"'
    light_kitchen_40: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/40"'
    light_kitchen_50: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/50"'
    light_kitchen_60: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/60"'
    light_kitchen_70: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/70"'
    light_kitchen_80: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/80"'
    light_kitchen_90: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/90"'
    light_kitchen_100: 'curl -X GET "http://192.168.1.12:9000/exec/light/Küche/2/100"'
    
    light_bathroom_headlights_0: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/2/Switch%20Off"'
    light_bathroom_headlights_1: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/2/Switch%20On"'
    light_bathroom_0: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/Switch%20Off"'
    light_bathroom_1: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/Switch%20On"'
    light_bathroom_10: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/10"'
    light_bathroom_20: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/20"'
    light_bathroom_30: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/30"'
    light_bathroom_40: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/40"'
    light_bathroom_50: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/50"'
    light_bathroom_60: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/60"'
    light_bathroom_70: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/70"'
    light_bathroom_80: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/80"'
    light_bathroom_90: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/90"'
    light_bathroom_100: 'curl -X GET "http://192.168.1.12:9000/exec/light/WC-Dusche/1/100"'

    light_entrance_0: 'curl -X GET "http://192.168.1.12:9000/exec/light/Entrée/1/Switch%20Off"'
    light_entrance_1: 'curl -X GET "http://192.168.1.12:9000/exec/light/Entrée/1/Switch%20On"'
    
    light_loggia_0: 'curl -X GET "http://192.168.1.12:9000/exec/light/Loggia/1/Switch%20Off"'
    light_loggia_1: 'curl -X GET "http://192.168.1.12:9000/exec/light/Loggia/1/Switch%20On"'

    ventilation_bedroom_0: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Zimmer%201/1/Aus"'
    ventilation_bedroom_1: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Zimmer%201/1/Stufe%201"'
    ventilation_bedroom_2: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Zimmer%201/1/Stufe%202"'
    ventilation_bedroom_3: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Zimmer%201/1/Stufe%203"'
    ventilation_bedroom_4: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Zimmer%201/1/Stufe%204"'
    
    ventilation_livingroom_0: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Wohnzimmer/1/Aus"'
    ventilation_livingroom_1: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Wohnzimmer/1/Stufe%201"'
    ventilation_livingroom_2: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Wohnzimmer/1/Stufe%202"'
    ventilation_livingroom_3: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Wohnzimmer/1/Stufe%203"'
    ventilation_livingroom_4: 'curl -X GET "http://192.168.1.12:9002/exec/ventilation/Wohnzimmer/1/Stufe%204"'
    
    shades_loggia_easy: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/1,2/20,40"'
    shades_loggia_privacy: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/1,2/100,50"'
    shades_loggia_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/1,2/0"'
    shades_loggia_60: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/1,2/60"'
    shades_loggia_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/1,2/100"'
    shades_loggia_side1_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/1/0"'
    shades_loggia_side1_60: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/1/60"'
    shades_loggia_side1_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/1/100"'
    shades_loggia_side2_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/2/0"'
    shades_loggia_side2_60: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/2/60"'
    shades_loggia_side2_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Loggia/2/100"'
    
    shades_bedroom_easy: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Zimmer%201/1/33?tilt=2"'
    shades_bedroom_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Zimmer%201/1/0?tilt=0"'
    shades_bedroom_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Zimmer%201/1/60?tilt=1"'
    shades_bedroom_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Zimmer%201/1/100?tilt=0"'    
    
    shades_kitchen_easy: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Küche/1/66?tilt=1"'
    shades_kitchen_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Küche/1/0?tilt=0"'
    shades_kitchen_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Küche/1/60?tilt=1"'
    shades_kitchen_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Küche/1/100?tilt=0"'
   
    shades_livingroom_easy: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3/50?tilt=1"'
    shades_livingroom_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3/0?tilt=0"'
    shades_livingroom_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3/60?tilt=1"'
    shades_livingroom_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3/100?tilt=0"'
    
    shades_loggiawindow_easy: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/4/100?tilt=2&type=Loggia"'
    shades_loggiawindow_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/4/0?tilt=0&type=Loggia"'
    shades_loggiawindow_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/4/60?tilt=1&type=Loggia"'
    shades_loggiawindow_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/4/100?tilt=0&type=Loggia"'
    
    shades_livingroom_loggia_easy: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3,4/50?tilt=1"'
    shades_livingroom_0_loggia_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3,4/0?tilt=0"'
    shades_livingroom_60_1_loggia_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3,4/60?tilt=1"'
    shades_livingroom_60_2_loggia_60_2: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3,4/60?tilt=2"'
    shades_livingroom_100_loggia_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/3,4/100?tilt=0"'
    
    shades_office_easy: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/2/66?tilt=1"'
    shades_office_0: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/2/0?tilt=0"'
    shades_office_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/2/60?tilt=1"'
    shades_office_100: 'curl -X GET "http://192.168.1.12:9001/exec/jalousie/Wohnzimmer/2/100?tilt=0"'

