  # Loads default set of integrations. Do not remove.
  default_config:

  # Load frontend themes from the themes folder
  frontend:
    themes: !include_dir_merge_named themes

  automation: !include automations.yaml
  script: !include scripts.yaml
  scene: !include scenes.yaml

  http:
    use_x_forwarded_for: true
    trusted_proxies:
      - 172.30.33.2

  shell_command:
    light_kitchen_headlights_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchenHeadlights=1&actionKitchen=Switch%20Off"'
    light_kitchen_headlights_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchenHeadlights=1&actionKitchen=Switch%20On"'
    light_kitchen_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=Switch%20Off"'
    light_kitchen_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=Switch%20On"'
    light_kitchen_10: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=10"'
    light_kitchen_20: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=20"'
    light_kitchen_30: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=30"'
    light_kitchen_40: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=40"'
    light_kitchen_50: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=50"'
    light_kitchen_60: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=60"'
    light_kitchen_70: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=70"'
    light_kitchen_80: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=80"'
    light_kitchen_90: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=90"'
    light_kitchen_100: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withKitchen=1&percentKitchen=100"'
    
    light_bathroom_headlights_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroomHeadlights=1&actionBathroom=Switch%20Off"'
    light_bathroom_headlights_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroomHeadlights=1&actionBathroom=Switch%20On"'
    light_bathroom_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=Switch%20Off"'
    light_bathroom_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=Switch%20On"'
    light_bathroom_10: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=10"'
    light_bathroom_20: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=20"'
    light_bathroom_30: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=30"'
    light_bathroom_40: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=40"'
    light_bathroom_50: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=50"'
    light_bathroom_60: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=60"'
    light_bathroom_70: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=70"'
    light_bathroom_80: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=80"'
    light_bathroom_90: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=90"'
    light_bathroom_100: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withBathroom=1&percentBathroom=100"'

    light_entrance_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withEntrance=1&actionEntrance=Switch%20Off"'
    light_entrance_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withEntrance=1&actionEntrance=Switch%20On"'
    
    light_loggia_0: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withLoggia=1&actionLoggia=Switch%20Off"'
    light_loggia_1: 'curl -X GET "http://192.168.1.12:9000/exec/518-light?withLoggia=1&actionLoggia=Switch%20On"'

    ventilation_bedroom_0: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Aus"'
    ventilation_bedroom_1: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Stufe 1"'
    ventilation_bedroom_2: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Stufe 2"'
    ventilation_bedroom_3: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Stufe 3"'
    ventilation_bedroom_4: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withBedroom=1&setBedroom=Stufe 4"'
    
    ventilation_livingroom_0: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Aus"'
    ventilation_livingroom_1: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Stufe 1"'
    ventilation_livingroom_2: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Stufe 2"'
    ventilation_livingroom_3: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Stufe 3"'
    ventilation_livingroom_4: 'curl -X GET "http://192.168.1.12:9002/exec/518-ventilation?withLivingroom=1&setLivingroom=Stufe 4"'
    
    shades_loggia_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1,2&setLoggia1=0&setLoggia2=0"'
    shades_loggia_60: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1,2&setLoggia1=60&setLoggia2=60"'
    shades_loggia_100: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Loggia&lgBlockIndex=1,2&setLoggia1=100&setLoggia2=100"'
    
    shades_bedroom: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom"'
    shades_bedroom_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=0"'
    shades_bedroom_30_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=30&brFinalPosition=1"'
    shades_bedroom_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=60&brFinalPosition=1"'
    shades_bedroom_90_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=90&brFinalPosition=1"'    
    shades_bedroom_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=100&brFinalPosition=1"'    
    shades_bedroom_100_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=100&brFinalPosition=0"'    
    
    shades_bedroom_30_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=30&brFinalPosition=2"'
    shades_bedroom_60_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=60&brFinalPosition=2"'
    shades_bedroom_90_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=90&brFinalPosition=2"'    
    shades_bedroom_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Bedroom&brPercent=100&brFinalPosition=2"'    
    
    shades_kitchen: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen"'
    shades_kitchen_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=0"'
    shades_kitchen_30_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=30&kcFinalPosition=0"'
    shades_kitchen_60_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=60&kcFinalPosition=0"'
    shades_kitchen_90_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=90&kcFinalPosition=0"'
    shades_kitchen_100_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=100&kcFinalPosition=0"'
   
    shades_kitchen_30_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=30&kcFinalPosition=1"'
    shades_kitchen_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=60&kcFinalPosition=1"'
    shades_kitchen_90_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=90&kcFinalPosition=1"'
    shades_kitchen_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=100&kcFinalPosition=1"'
    
    shades_kitchen_30_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=30&kcFinalPosition=2"'
    shades_kitchen_60_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=60&kcFinalPosition=2"'
    shades_kitchen_90_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=90&kcFinalPosition=2"'
    shades_kitchen_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Kitchen&kcPercent=100&kcFinalPosition=2"'
    
    shades_livingroom: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom"'
    shades_livingroom_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=0&percent3=0"'
    shades_livingroom_30_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=30&finalPosition2=0&percent3=30&finalPosition3=0"'
    shades_livingroom_60_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=60&finalPosition2=0&percent3=60&finalPosition3=0"'
    shades_livingroom_90_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=90&finalPosition2=0&percent3=90&finalPosition3=0"'
    shades_livingroom_100_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=100&finalPosition2=0&percent3=100&finalPosition3=0"'

    shades_livingroom_30_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=30&finalPosition2=1&percent3=30&finalPosition3=1"'
    shades_livingroom_60_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=60&finalPosition2=1&percent3=60&finalPosition3=1"'
    shades_livingroom_90_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=90&finalPosition2=1&percent3=90&finalPosition3=1"'
    shades_livingroom_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=100&finalPosition2=1&percent3=100&finalPosition3=1"'
    
    shades_livingroom_30_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=30&finalPosition2=2&percent3=30&finalPosition3=2"'
    shades_livingroom_60_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=60&finalPosition2=2&percent3=60&finalPosition3=2"'
    shades_livingroom_90_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=90&finalPosition2=2&percent3=90&finalPosition3=2"'
    shades_livingroom_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&percent2=100&finalPosition2=2&percent3=100&finalPosition3=2"'

    shades_livingroom_loggia: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1"'
    shades_livingroom_0_loggia_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=0&percent3=0&percent4=0"'
    shades_livingroom_30_0_loggia_50_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=0&percent3=30&finalPosition3=0&percent4=50&finalPosition4=0"'
    shades_livingroom_60_0_loggia_50_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=0&percent3=60&finalPosition3=0&percent4=50&finalPosition4=0"'
    shades_livingroom_90_0_loggia_50_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=0&percent3=90&finalPosition3=0&percent4=50&finalPosition4=0"'
    shades_livingroom_100_0_loggia_50_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=0&percent3=100&finalPosition3=0&percent4=50&finalPosition4=0"'

    shades_livingroom_30_1_loggia_50_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=1&percent3=30&finalPosition3=1&percent4=50&finalPosition4=1"'
    shades_livingroom_60_1_loggia_50_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=1&percent3=60&finalPosition3=1&percent4=50&finalPosition4=1"'
    shades_livingroom_90_1_loggia_50_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=1&percent3=90&finalPosition3=1&percent4=50&finalPosition4=1"'
    shades_livingroom_100_1_loggia_50_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=1&percent3=100&finalPosition3=1&percent4=50&finalPosition4=1"'
    
    shades_livingroom_30_1_loggia_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=1&percent3=30&finalPosition3=1&percent4=100&finalPosition4=1"'
    shades_livingroom_60_1_loggia_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=1&percent3=60&finalPosition3=1&percent4=100&finalPosition4=1"'
    shades_livingroom_90_1_loggia_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=1&percent3=90&finalPosition3=1&percent4=100&finalPosition4=1"'
    shades_livingroom_100_1_loggia_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=1&percent3=100&finalPosition3=1&percent4=100&finalPosition4=1"'
    
    shades_livingroom_100_0_loggia_100_0: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=0&percent3=100&finalPosition3=0&percent4=100&finalPosition4=0"'

    shades_livingroom_30_1_loggia_50_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=1&percent3=30&finalPosition3=1&percent4=50&finalPosition4=2"'
    shades_livingroom_60_1_loggia_50_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=1&percent3=60&finalPosition3=1&percent4=50&finalPosition4=2"'
    shades_livingroom_90_1_loggia_50_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=1&percent3=90&finalPosition3=1&percent4=50&finalPosition4=2"'
    shades_livingroom_100_1_loggia_50_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=1&percent3=100&finalPosition3=1&percent4=50&finalPosition4=2"'
    
    shades_livingroom_30_1_loggia_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=1&percent3=30&finalPosition3=1&percent4=100&finalPosition4=2"'
    shades_livingroom_60_1_loggia_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=1&percent3=60&finalPosition3=1&percent4=100&finalPosition4=2"'
    shades_livingroom_90_1_loggia_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=1&percent3=90&finalPosition3=1&percent4=100&finalPosition4=2"'
    shades_livingroom_100_1_loggia_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=1&percent3=100&finalPosition3=1&percent4=100&finalPosition4=2"'
    
    shades_livingroom_30_2_loggia_50_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=2&percent3=30&finalPosition3=2&percent4=50&finalPosition4=1"'
    shades_livingroom_60_2_loggia_50_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=2&percent3=60&finalPosition3=2&percent4=50&finalPosition4=1"'
    shades_livingroom_90_2_loggia_50_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=2&percent3=90&finalPosition3=2&percent4=50&finalPosition4=1"'
    shades_livingroom_100_2_loggia_50_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=2&percent3=100&finalPosition3=2&percent4=50&finalPosition4=1"'
    
    shades_livingroom_30_2_loggia_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=2&percent3=30&finalPosition3=2&percent4=100&finalPosition4=1"'
    shades_livingroom_60_2_loggia_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=2&percent3=60&finalPosition3=2&percent4=100&finalPosition4=1"'
    shades_livingroom_90_2_loggia_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=2&percent3=90&finalPosition3=2&percent4=100&finalPosition4=1"'
    shades_livingroom_100_2_loggia_100_1: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=2&percent3=100&finalPosition3=2&percent4=100&finalPosition4=1"'
    
    shades_livingroom_30_2_loggia_50_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=2&percent3=30&finalPosition3=2&percent4=50&finalPosition4=2"'
    shades_livingroom_60_2_loggia_50_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=2&percent3=60&finalPosition3=2&percent4=50&finalPosition4=2"'
    shades_livingroom_90_2_loggia_50_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=2&percent3=90&finalPosition3=2&percent4=50&finalPosition4=2"'
    shades_livingroom_100_2_loggia_50_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=2&percent3=100&finalPosition3=2&percent4=50&finalPosition4=2"'
    
    shades_livingroom_30_2_loggia_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=30&finalPosition2=2&percent3=30&finalPosition3=2&percent4=100&finalPosition4=2"'
    shades_livingroom_60_2_loggia_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=60&finalPosition2=2&percent3=60&finalPosition3=2&percent4=100&finalPosition4=2"'
    shades_livingroom_90_2_loggia_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=90&finalPosition2=2&percent3=90&finalPosition3=2&percent4=100&finalPosition4=2"'
    shades_livingroom_100_2_loggia_100_2: 'curl -X GET "http://192.168.1.12:9001/exec/518-shades?room=Livingroom&lg=1&percent2=100&finalPosition2=2&percent3=100&finalPosition3=2&percent4=100&finalPosition4=2"'
